services:
  ea-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-dashboard
    ports:
      - '8899:8899'
    restart: always
    environment:
      - NODE_ENV=production
