services:
  ea-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-dashboard
    ports:
      - '4000:80'
    restart: always
    environment:
      - NODE_ENV=production
